# Generated by Django 2.2.28 on 2023-09-11 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_id', models.PositiveIntegerField()),
                ('reason', models.PositiveSmallIntegerField(choices=[(1, 'Unsolicited commercial content'), (2, 'Explicit adult material'), (3, 'Malicious and abusive behavior'), (4, 'Violent, graphic, and harmful material'), (5, 'Child exploitation imagery'), (6, 'Criminal actions (e.g. drug-related activities)t'), (7, 'Misleading information'), (8, 'Violation of copyright and trademark rights'), (9, 'Self-destructive actions'), (10, 'Others')], default=10)),
                ('other', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_to_content', to='contenttypes.ContentType')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Content',
            },
        ),
    ]
