# Generated by Django 2.2.28 on 2022-09-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20200724_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneraddress',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partneraddress',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
