# Generated by Django 3.2.13 on 2022-05-18 18:49

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=20)),
                ('definition_id', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('choices', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='FormAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=200)),
                ('form_definition_id', models.ForeignKey(db_column='definition_id', on_delete=django.db.models.deletion.CASCADE, to='restapis.formdefinition', to_field='definition_id')),
            ],
        ),
    ]
