# Generated by Django 2.2.24 on 2022-03-15 09:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('two-factor-authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('verify', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
