# Generated by Django 2.2.27 on 2022-03-15 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('two-factor-authentication', '0002_auto_20220315_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='verify',
        ),
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('phone_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='two-factor-authentication.PhoneNumber')),
            ],
        ),
    ]
