# Generated by Django 2.2.27 on 2022-03-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two-factor-authentication', '0003_auto_20220315_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
