# Generated by Django 2.2.27 on 2022-03-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two-factor-authentication', '0004_auto_20220315_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
