# Generated by Django 2.2.27 on 2022-03-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two-factor-authentication', '0006_auto_20220317_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
