# Generated by Django 2.2.27 on 2022-03-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two-factor-authentication', '0007_auto_20220322_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneNumber',
            new_name='TwoFactorAuth',
        ),
    ]
