# Generated by Django 3.2.20 on 2023-09-18 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'type', 'id'], unique=True)),
                ('type', models.CharField(choices=[('BOOLEAN', 'Boolean'), ('DECIMAL', 'Decimal'), ('INTEGER', 'Integer'), ('CHOICE', 'Choice'), ('MULTI_SELECT', 'Multi Select')], max_length=256)),
            ],
            options={
                'verbose_name_plural': 'App Settings',
            },
        ),
        migrations.CreateModel(
            name='StateChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=256)),
                ('default_choice', models.BooleanField(default=False)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_settings', to='settings.settings')),
            ],
            options={
                'verbose_name_plural': 'Settings Choices',
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='default_choice',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_default_state', to='settings.statechoices'),
        ),
        migrations.CreateModel(
            name='UserAppSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_choices', models.ManyToManyField(to='settings.StateChoices')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_app_setting', to='settings.settings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Settings',
                'unique_together': {('user', 'setting')},
            },
        ),
    ]
