export const USER_READ = 'USER_READ';
export const USER_READ_SUCCEEDED = 'USER_READ_SUCCEEDED';
export const USER_READ_FAILED = 'USER_READ_FAILED';

export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_SUCCEEDED = 'USER_UPDATE_SUCCEEDED';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';

export const USER_LIST = 'USER_LIST';
export const USER_LIST_SUCCEEDED = 'USER_LIST_SUCCEEDED';
export const USER_LIST_FAILED = 'USER_LIST_FAILED';
