# Generated by Django 2.2.28 on 2022-09-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20210210_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_class'),
        ),
    ]
