# Generated by Django 2.2.28 on 2022-09-21 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_auto_20220920_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptiongroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_option_groups', to='catalogue.Product'),
        ),
    ]
