# Generated by Django 2.2.28 on 2022-09-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20220921_0928'),
        ('catalogue', '0025_auto_20220919_0251'),
    ]

    operations = [
    ]
