# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
# Opt out of sending fastlane usage metrics

@base_name = 'HelloWorld'

import_from_git(
  url: "git@github.com:crowdbotics/fastlane-config.git", # The URL of the repository to import the Fastfile from.
  branch: "#{ENV.fetch('FASTLANE_CONFIG_VERSION', "master")}", # The branch to checkout on the repository.
  path: "android/Fastfile", # The path of the Fastfile in the repository.
)
