source "https://rubygems.org"

gem "fastlane", "~>2.137"
gem "httparty", "~>0.17"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
