# Generated by Django 2.2.24 on 2022-04-27 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField(default=datetime.timedelta)),
                ('location', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
