export const API_LOGIN_REQUEST = 'API_LOGIN_REQUEST';
export const API_LOGIN_SUCCESS = 'API_LOGIN_SUCCESS';
export const API_LOGIN_FAILED = 'API_LOGIN_FAILED';

export const API_LOGOUT_REQUEST = 'API_LOGOUT_REQUEST';
export const API_LOGOUT_SUCCESS = 'API_LOGOUT_SUCCESS';
export const API_LOGOUT_FAILED = 'API_LOGOUT_FAILED';

export const API_SIGNUP_REQUEST = 'API_SIGNUP_REQUEST';
export const API_SIGNUP_SUCCESS = 'API_SIGNUP_SUCCESS';
export const API_SIGNUP_FAILED = 'API_SIGNUP_FAILED';

export const API_PASSWORD_RESET_REQUEST = 'API_PASSWORD_RESET_REQUEST';
export const API_PASSWORD_RESET_SUCCESS = 'API_PASSWORD_RESET_SUCCESS';
export const API_PASSWORD_RESET_FAILED = 'API_PASSWORD_RESET_FAILED';

export const API_FACEBOOK_CONNECT = 'API_FACEBOOK_CONNECT_REQUEST';
export const API_FACEBOOK_CONNECT_SUCCESS = 'API_FACEBOOK_CONNECT_SUCCESS';
export const API_FACEBOOK_CONNECT_FAILED = 'API_FACEBOOK_CONNECT_FAILED';

export const API_GOOGLE_CONNECT = 'API_GOOGLE_CONNECT_REQUEST';
export const API_GOOGLE_CONNECT_SUCCESS = 'API_GOOGLE_CONNECT_SUCCESS';
export const API_GOOGLE_CONNECT_FAILED = 'API_GOOGLE_CONNECT_FAILED';


