# Generated by Django 2.2.28 on 2023-01-02 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointment.BaseModel')),
                ('type_tag', models.CharField(max_length=220)),
                ('type_text', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'MeetingTypes',
            },
            bases=('appointment.basemodel',),
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointment.BaseModel')),
                ('title', models.CharField(max_length=220, verbose_name='meeting title')),
                ('description', models.CharField(blank=True, max_length=220, null=True)),
                ('html_link', models.URLField(blank=True, null=True)),
                ('hang_out', models.URLField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='meeting start time')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='meeting end time')),
                ('meeting_id', models.CharField(blank=True, max_length=220, null=True)),
                ('organizer', models.EmailField(max_length=254, verbose_name="organizer's email")),
                ('location', models.CharField(blank=True, max_length=220, null=True)),
                ('status', models.CharField(blank=True, max_length=220, null=True)),
                ('summary', models.CharField(blank=True, max_length=220, null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_type', to='appointment.MeetingType')),
            ],
            options={
                'verbose_name_plural': 'Meetings',
            },
            bases=('appointment.basemodel',),
        ),
        migrations.CreateModel(
            name='MeetingAttendees',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointment.BaseModel')),
                ('email', models.EmailField(max_length=254, verbose_name="attendee's email")),
                ('response_status', models.CharField(blank=True, max_length=220, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_to_attends', to='appointment.Meetings')),
            ],
            options={
                'verbose_name_plural': 'MeetingAttendees',
            },
            bases=('appointment.basemodel',),
        ),
    ]
