# Generated by Django 2.2.24 on 2022-03-19 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('subscription', '0004_auto_20220319_1624'), ('subscription', '0005_auto_20220319_1631'), ('subscription', '0006_usersubscription_subscription_id')]

    dependencies = [
        ('subscription', '0003_auto_20220319_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='interval',
            field=models.CharField(blank=True, help_text='Filled Automatically by pulling from stripe according to price_id', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(blank=True, help_text='Filled Automatically by pulling from stripe according to price_id', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Filled Automatically by pulling from stripe according to price_id', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tier_user_subscriptions', to='subscription.SubscriptionPlan'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
