# Generated by Django 2.2.24 on 2022-03-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20220319_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='interval',
            field=models.CharField(blank=True, help_text='Filled Automatically by pulling from stripe according to price_id', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(blank=True, help_text='Filled Automatically by pulling from stripe according to price_id', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Filled Automatically by pulling from stripe according to price_id', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
