# Generated by Django 2.2.24 on 2022-03-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20220319_1624_squashed_0006_usersubscription_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
