# Generated by Django 2.2.24 on 2022-03-19 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20220319_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tier_user_subscriptions', to='subscription.SubscriptionPlan'),
        ),
    ]
