# Generated by Django 2.2.24 on 2022-03-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20220319_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
