# Generated by Django 3.2.23 on 2023-12-23 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('open_ai_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, choices=[('gpt-3.5-turbo', 'gpt-3.5-turbo'), ('gpt-3.5-turbo-1106', 'gpt-3.5-turbo-1106'), ('gpt-3.5-turbo-16k', 'gpt-3.5-turbo-16k'), ('gpt-4-0314', 'gpt-4-0314')], max_length=255, null=True)),
                ('max_tokens', models.IntegerField(blank=True, default=1000, null=True)),
                ('use_context', models.BooleanField(default=True, help_text='Use context from previous messages')),
                ('context_length', models.IntegerField(blank=True, default=3, help_text='Number of previous messages to use as context', null=True)),
                ('only_questions_in_context', models.BooleanField(default=False, help_text='Only use questions in context')),
                ('summarize_context', models.BooleanField(default=True, help_text='use summary as context')),
                ('initial_context', models.TextField(blank=True, help_text='Initial context to use e.g. You are a crowdbotics assistant.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this config active')),
                ('global_config', models.BooleanField(default=False, help_text='Is this config global')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OpenAI Config',
                'verbose_name_plural': 'OpenAI Configs',
                'unique_together': {('is_active', 'global_config')},
            },
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_ai_chat.openaiconfig')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
