version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "13:00"
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/backend"
    schedule:
      interval: weekly
      day: sunday
      time: "13:00"
    open-pull-requests-limit: 10
    # Avoid major upgrades since they may not be compatible with the Crowdbotics ecosystem
    versioning-strategy: lockfile-only
