version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.1.0
jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run: 
          name: Generate Pipeline generated_config.yml file
          command: |
            if [ "$BUILD_TYPE" == "mobile" ]; then
              bash .circleci/generate_mobile_config.sh
            elif [ "$BUILD_TYPE" == "gcp" ]; then
              bash backend/.circleci/generate_gcp_config.sh "backend/"
            fi
      - continuation/continue:
          parameters: '{}'
          configuration_path: configs/generated_config.yml
workflows:
  setup-workflow:
    jobs:
      - setup