# Generated by Django 2.2.24 on 2022-05-16 10:19

from django.db import migrations, models
import modules.signature.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=modules.signature.models.nameFile)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]