# Generated by Django 2.2.28 on 2022-09-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_auto_20220919_0251'),
        ('basket', '0010_auto_20220921_0928'),
    ]

    operations = [
    ]
