name: Create release notes and sync JIRA

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./modules

    steps:
      - name: Repo Clone 
        run: |
          git clone https://${{ secrets.GIT_TOKEN }}@github.com/crowdbotics/modules.git
      
      - name: Checkout branch
        working-directory: ${{ env.working-directory }}
        run: | 
          echo "branch: ${GITHUB_REF_NAME}"
          git checkout ${GITHUB_REF_NAME}

      - name: Run Release Workflow
        uses: crowdbotics/github-actions/create-github-release@master
        with:
          working-directory: ${{ env.working-directory }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}