name: Lint

on:
  pull_request:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn install
      - uses: danielsousaio/action-eslint@220fde5fb47094f54a96995c4ea1eb6cb1cd05c1
        with:
          eslint-args: "--config .eslintrc.json --ignore-path=.gitignore --quiet"
          extensions: "js,jsx,ts,tsx"
          annotations: true
