export const API_LOGIN_REQUEST = 'API_LOGIN_REQUEST';
export const API_LOGIN_SUCCESS = 'API_LOGIN_SUCCESS';
export const API_LOGIN_FAILED = 'API_LOGIN_FAILED';

export const API_LOGOUT_REQUEST = 'API_LOGOUT_REQUEST';
export const API_LOGOUT_SUCCESS = 'API_LOGOUT_SUCCESS';
export const API_LOGOUT_FAILED = 'API_LOGOUT_FAILED';

export const API_SIGNUP_REQUEST = 'API_SIGNUP_REQUEST';
export const API_SIGNUP_SUCCESS = 'API_SIGNUP_SUCCESS';
export const API_SIGNUP_FAILED = 'API_SIGNUP_FAILED';

export const API_PASSWORD_RESET_REQUEST = 'API_PASSWORD_RESET_REQUEST';
export const API_PASSWORD_RESET_SUCCESS = 'API_PASSWORD_RESET_SUCCESS';
export const API_PASSWORD_RESET_FAILED = 'API_PASSWORD_RESET_FAILED';

